generate-coverage:
	dart ci/generate_coverage_helper.dart
	flutter test --coverage

run-cli-output: generate-coverage
	git diff origin/main | dart bin/pull_request_coverage.dart  --maximum-uncovered-lines 5 --minimum-coverage 99 --output-mode cli


run-cli-no-color-output: generate-coverage
	git diff origin/main | dart bin/pull_request_coverage.dart --maximum-uncovered-lines 5 --minimum-coverage 99 --output-mode cli --use-colorful-output false

run-markdown-output: generate-coverage
	git diff origin/main | dart bin/pull_request_coverage.dart  --maximum-uncovered-lines 5 --minimum-coverage 99 --output-mode markdown

run-markdown-no-color-output: generate-coverage
	git diff origin/main | dart bin/pull_request_coverage.dart --maximum-uncovered-lines 5 --minimum-coverage 99 --output-mode markdown --use-colorful-output false